version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - run:
          command: git clone --recursive https://github.com/pi-hole/pi-hole.git ~/project
          name: "Clone Pi-Hole main repository"
          working_directory: ~/project
      - run:
          command: pip install -r requirements.txt
          name: "Install requirements"
      - checkout
      - python/dist

workflows:
  main:
    jobs:
      - build

