version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - run:
          command: git clone --recursive https://github.com/pi-hole/pi-hole.git ~/pi-hole
          name: "Clone Pi-Hole main repository"
          working_directory: ~/pi-hole
      - checkout
      - python/install-deps:
          app-dir: ~/pi-hole
      - python/dist:
          app-dir: ~/pi-hole

workflows:
  main:
    jobs:
      - build

