version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - run:
          command: git clone --recursive https://github.com/pi-hole/pi-hole.git ~/project
          name: "Clone Pi-Hole main repository"
          working_directory: ~/project
      - checkout:
          path: ~/project/.orb
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/dist

workflows:
    build:
        jobs:
            - build
            - orb-tools/lint
            - orb-tools/pack
            - hold-for-publish:
                  type: approval
                  requires:
                      - orb-tools/lint
                      - orb-tools/pack
            - orb-tools/publish:
                  attach-workspace: true
                  orb-ref: xmate420x/pi-hole@1.0.0
                  context: pub
                  requires: [hold-for-publish]
