version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - run:
          command: git clone --recursive https://github.com/pi-hole/pi-hole.git ~
          name: "Clone Pi-Hole main repository"
          working_directory: ~
      - checkout
      - python/install-deps
      - python/dist:
          app-dir: ~

workflows:
  main:
    jobs:
      - build

