version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: git clone --recursive https://github.com/pi-hole/pi-hole.git ~/project
          name: "Clone Pi-Hole main repository"
          working_directory: ~/project
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/dist

workflows:
  main:
    jobs:
      - build

